apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: amt-enhetsregister-alerts
  namespace: amt
  labels:
    team: amt
spec:
  receivers:
    slack:
      channel: 'team_komet_dev_alerts'
      prependText: ' | '
  alerts:
    - alert: applikasjon nede
      expr: kube_deployment_status_replicas_available{deployment="amt-enhetsregister"} == 0
      for: 2m
      description: "App amt-enhetsregister er nede i namespace amt-enhetsregister"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n amt-enhetsregister` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n amt-enhetsregister` for logger"
      severity: danger
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="amt-enhetsregister",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="amt-enhetsregister"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app amt-enhetsregister i namespace amt, for å se hvorfor det er så mye feil"
