kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-enhetsregister
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-enhetsregister.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 50
  liveness:
    path: /internal/health/liveness
    initialDelay: 50
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 4096Mi # Trenger mye minne når man skal laste ned alle enheter
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-arrangor
          namespace: amt
          cluster: dev-gcp
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: dev-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
    outbound:
      external:
        - host: data.brreg.no
  kafka:
    pool: nav-dev
  env:
    # Kafka topics
    - name: VIRKSOMHETER_TOPIC
      value: amt.virksomheter-v1

  gcp:
    sqlInstances:
      - name: amt-enhetsregister-v1
        tier: db-custom-1-3840
        type: POSTGRES_14
        databases:
          - name: amt-enhetsregister
            envVarPrefix: DB

  observability:
      autoInstrumentation:
        enabled: true
        runtime: java
      logging:
        destinations:
          - id: elastic
          - id: loki
