kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-enhetsregister
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-enhetsregister/amt-enhetsregister:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 4096Mi # Trenger mye minne når man skal laste ned alle enheter
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
          namespace: amt
          cluster: prod-gcp
        - application: arena-aktivitet-acl
          namespace: dab
          cluster: prod-gcp
    outbound:
      external:
        - host: data.brreg.no
  gcp:
    sqlInstances:
      - name: amt-enhetsregister-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskAutoresize: true
        databases:
          - name: amt-enhetsregister
            envVarPrefix: DB

