server.port=8085
AZURE_APP_WELL_KNOWN_URL=http://localhost:9000/azure/.well-known/openid-configuration
AZURE_APP_CLIENT_ID=amt-enhetsregister
DB_JDBC_URL=jdbc:postgresql://localhost:5432/amt_enhetsregister_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

app.env.brreg-url=http://localhost:9002/brreg

