name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts-prod.yaml'
      - '.github/workflows/deploy-alerts-prod.yaml'
jobs:
  apply-alerts:
    permissions:
      id-token: "write"
    name: Apply alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts-prod.yaml
